### ISSUE TITLE
fix z-index

### ISSUE THREAD

**Issue by jasomdotnet** [englishextra/iframe-lightbox#10]
Set 'z-index' css property for `.iframe-lightbox` class to `999`. `2` is not enough (bug can be see in latest [WordPress theme](https://privnote.com/RlGMSiIj#uFw8tx6zq)).

PS: There is also `z-index: 2;` in `.iframe-lightbox .content-holder` I didn't investigate this.

**Comment by englishextra** [comment]
@jasomdotnet Hi thanks for your support.

Could you please clone the latest commit and check whether all works as designed (together with the wordpress theme you are using)

That would be helpful before I publish a fixed 0.1.9 version on NPM

**Comment by jasomdotnet** [comment]
increase z-index to `999999` because `#wpadminbar` z-index is `99999`.
