### ISSUE TITLE
It is possible to fix background when iframe is active?

### ISSUE THREAD

**Issue by jasomdotnet** [englishextra/iframe-lightbox#12]
It is possible to fix background when iframe is active? Now it moves when miss-clicked, scrolled or miss-toutch on mobile. See [this](https://privnote.com/eOKmIQvP#MBiatIEZT) video*.

* video was recorded in FF without today .css commits.

**Comment by englishextra** [comment]
You mean to freeze body scrolling when the lightbox is open - it is usualy made with position fixed to body or height auto. But I have to see about it. Or more safe way to add class to html and body say - html.iframe-lightbox-open so tha you can make your own fixes foer instance  html.iframe-lightbox-open {height:auto;} It depends what is your setup that goes down in your css rules. I need some time to test

**Comment by englishextra** [comment]
Just commited a fix - so generally you don't need to write fixes of your own.

**Comment by jasomdotnet** [comment]
I just linked to my WP site master version of unminified `.js` and `.css` from IFLI :) so you can test it on the fly (no need to wait on me).

PS: Fixed BG works.
