### ISSUE TITLE
minify iframe-lightbox.min.css more

### ISSUE THREAD

**Issue by jasomdotnet** [englishextra/iframe-lightbox#17]
[There](https://github.com/englishextra/iframe-lightbox/blob/master/css/iframe-lightbox.min.css) is too much comments. With this [tool](https://csscompressor.com/) can by minified 26% more.

**Comment by englishextra** [comment]
@jasomdotnet v0.2.6

`https://cdn.jsdelivr.net/gh/englishextra/iframe-lightbox@0.2.6/js/iframe-lightbox.min.js`

`https://cdn.jsdelivr.net/gh/englishextra/iframe-lightbox@0.2.6/css/iframe-lightbox.min.css`

Please update JS as well - important fix there https://github.com/englishextra/iframe-lightbox/blob/master/CHANGELOG.md

**Comment by jasomdotnet** [comment]
iframe-lightbox.min.css now looks better.

**Comment by englishextra** [comment]
@jasomdotnet Please notice one issue

Since adding touchstart to surpress worpress theme setup for touch events on links leads to bad consequences in some use cases  -say - you have images placed into a link elemnt and those links with images are spread into a masonry grid - tiles, this will lead that you cannot scroll down on a narrow mobile screens where images have 100%  width - the lightbox will immediately launch, not letting you to scroll down.

So place in options object - {touch: true} - otherwise your wordpress theme script will again take over

This will be released in v0.2.7

**Comment by jasomdotnet** [comment]
okey, I will add this to my configuration.

**Comment by englishextra** [comment]
@jasomdotnet By the way if You use `data-src`, then you don't need to add `{touch:true}` because you will place `#` or `javascript:void(0)`, and wordpress theme wont harm:
`touch-keyboard-navigation.js`
```js
if ( '#' !== url && '' !== url ) {
					window.location = url;
```

**Comment by jasomdotnet** [comment]
So the most bullet-proof configuration (working in as much situations as possible) is to use  `data-src` together with `{touch:true}` or just `data-src` is enough?

**Comment by englishextra** [comment]
For those who don't use 3rd-party scripts that interfere with links behaviour and don't force `window.location` they have no need in either `data-touch="true"` or `{touch: true}`; they care only for `{scrolling: thru}` or `data-scrolling="true"`.
When you have scripts that interfere, then to keep lightbox working, use `{touch: true}` or `data-touch="true"`.
`data-src` or `href` doesn't matter, but you shouldn't enable `touch` override if you have a full screen image in a lighbox link and have no other space to scroll down.

**Comment by jasomdotnet** [comment]
Great, I saved this comment, maybe you want to add this to official documentation.

-- 

Also I suggest to clean non-minified [css](https://github.com/englishextra/iframe-lightbox/blob/master/css/iframe-lightbox.css). People are not interested about genesis of this file (I'm speaking about comments like `https://github.com/englishextra/iframe-lightbox/issues/12`);

**Comment by englishextra** [comment]
> Also I suggest to clean non-minified css. People are not interested about genesis of this file (I'm speaking about comments like https://github.com/englishextra/iframe-lightbox/issues/12);

I don't mind if you wipe up some genesis info in your comments - but I need to keep track why this or that commit been made
