### ISSUE TITLE
Feature request - pass iframe properties in

### ISSUE THREAD

**Issue by rtpHarry** [englishextra/iframe-lightbox#23]
I was wanting to use this to embed some virtual tour / 3d model type things from various providers.

However, they all stack up tons of extra properties on the iframes that aren't part of the link.

Some examples:

```
    <iframe frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" 
            allow="autoplay; fullscreen; xr-spatial-tracking" 
            xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share 
            src="https://sketchfab.com/models/{{asset_id|raw}}/embed?autospin=1&autostart=1&ui_infos=0"> </iframe>
```

```
    <iframe src="{{asset_id|raw}}" width="100%" frameborder="0" style="border:0" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
```

```
    <iframe width="100%" src="https://www.youtube-nocookie.com/embed/{{asset_id|raw}}?rel=0" title="YouTube video player" 
            frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
            allowfullscreen></iframe>
```

(The `{{asset_id|raw}}` tags are just how the Elementor Unlimited Elements widget passes properties through in my code)

I'm going to try embedding them using this anyway but I'm concerned that I cannot test all the features such as the xr-spatial-tracking, and I'm going to introduce hidden issues.

It would be nice to have some framework to pass this through, such as maybe any attributes on the link that start with `data-frame-{anything}` are added on as attributes to the iframe tag?

**Comment by englishextra** [comment]
@rtpHarry Could you please post here some `pseudo markup` to understand you idea?

**Comment by englishextra** [comment]
since no examples arrived I now close this issue
