### ISSUE TITLE
How to add properties to generated html5 video, audio and img tags

### ISSUE THREAD

**Issue by drnkwati** [englishextra/iframe-lightbox#4]
Hi
First great work man. I love this plugin for its simplicity and small size.
I have a feature request.
Can you add support for adding properties to data-src like html5 video, audio, and even img tags?
For example, i use this to open an html5 video:

<a href="javascript:void(0);" class="iframe-lightbox-link" data-src="/wip/assets/media/video.mp4" data-padding-bottom="56.25%"> HTML5 Video
 </a>

The video opens with iframe-lightbox in a video tag.
That's great but I wish we can set some properties on the video tag itself. 
Instead of:

<video autoplay="" controls="" style="position:absolute; top:0; left:0; width:100%; height:100%"></video>

I wish to add some properties like
<video autoplay="false" controls="" style="position:absolute; top:0; left:0; width:100%; height:100%"
poster="/wip/assets/media/poster.mp4"></video>

Can this be achieved? If not please kindly add this feature. Also, it should be applicable to audio, img tags as well.

thanks

**Comment by englishextra** [comment]
@drnkwati Thanks for your suggestion.

I'm afaraid there's nothing I can offer for your use case because:

> Scripts trying to access a frame's content are subject to the same-origin policy, and cannot access most of the properties in the other window object if it was loaded from a different domain. [The HTML iframe element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe)

Most of the content is acquired from another domain - Youtube Vimeo Soundcloud etc. Thus there's no possibility to manipulate DOM that belongs to an iframe content.

**Comment by englishextra** [comment]
I guess since no response received the issue can be closed.
