### ISSUE TITLE
Fails only when I add the preset class iframe-lightbox

### ISSUE THREAD

**Issue by PandaWood** [englishextra/iframe-lightbox#5]
You can ignore this, I was confused about which class to use in my HTML. I can't delete it

I was adding the class `iframe-lightbox` to my element - which was blowing up badly, because I now understand, this is the class that you've reserved to create within the js

**Comment by PandaWood** [comment]
Can I ask why the sample code uses the class `iframe-lightbox-link` but the CSS file (included) uses `iframe-lightbox` class. Are they meant to be the same?

**Comment by englishextra** [comment]
iframe- lightbox is used for styling of lightbox. while iframe-lightbox-link is used to select elements and has no stylying in the included css.
For links you can use any other class of yours or data attribute depending how you gonna
select those links.

```html
<a href="javascript:void(0);" class="iframe-lightbox-link" data-src="https://audiomack.com/embed/song/bottomfeedermusic/no-shame-explicit" data-padding-bottom="252px">Audiomack</a>
```


iframe-lightbox-link can have other name and you use it to find these links while iframe-lightbox is created dynamically with js when adding iframe element

сб, 14 июля 2018 г., 10:04 Peter van der Woude <notifications@github.com>:

**Comment by PandaWood** [comment]
My apologies, I was editing my first issue comment there because all the error and trouble I had was due to me using the wrong class.

It works OK now.
