### ISSUE TITLE
Allow scrolling

### ISSUE THREAD

**Issue by jasomdotnet** [englishextra/iframe-lightbox#6]
Add configuration (during initialization) allowing to scroll in iframed site.

**Comment by englishextra** [comment]
Solved https://github.com/englishextra/iframe-lightbox/issues/6 https://github.com/englishextra/iframe-lightbox/issues/7 https://github.com/englishextra/iframe-lightbox/issues/8

Published https://www.npmjs.com/package/iframe-lightbox

**Comment by englishextra** [comment]
in v0.2.2 you can:

> For Scrollable content set `data-scrolling="true"`, or add `scrolling` option property with `true`

https://github.com/englishextra/iframe-lightbox/tree/v0.2.2
