### ISSUE TITLE
Doesn't close when ESC button is pressed

### ISSUE THREAD

**Issue by jasomdotnet** [englishextra/iframe-lightbox#7]
Add functionality to close lightbox by ESCape keyaboard button.

**Comment by englishextra** [comment]
Solved https://github.com/englishextra/iframe-lightbox/issues/6 https://github.com/englishextra/iframe-lightbox/issues/7 https://github.com/englishextra/iframe-lightbox/issues/8

Published https://www.npmjs.com/package/iframe-lightbox
