### ISSUE TITLE
Add 'x' sign closing lightbox - users like to click on this

### ISSUE THREAD

**Issue by jasomdotnet** [englishextra/iframe-lightbox#8]
Add 'x' sign closing lightbox - users like to click on this and they expect this (older people are used to this).

**Comment by englishextra** [comment]
Solved https://github.com/englishextra/iframe-lightbox/issues/6 https://github.com/englishextra/iframe-lightbox/issues/7 https://github.com/englishextra/iframe-lightbox/issues/8

Published https://www.npmjs.com/package/iframe-lightbox
