### ISSUE TITLE
closing 'x' sign is not visible in Firefox.

### ISSUE THREAD

**Issue by jasomdotnet** [englishextra/iframe-lightbox#9]
closing 'x' sign is not visible in latest Firefox 64.

**Comment by jasomdotnet** [comment]
same for 'loading' spinner. Both SVG images embeded in css doesn't work in Firefox (also on FF for Android).

**Comment by englishextra** [comment]
@jasomdotnet Please  clone the repo - it has just updated and launch demo.html in FF IE11 Edge and Chrome. So that to make sure there isn't anything interferring from your custom setup. Thanks

**Comment by jasomdotnet** [comment]
I didn't get this part:

> So that to make sure there isn't anything interferring from your custom setup.

I don't want to "clone the repo". I like your script, just fix crossbrowser bugs :-)

Or you say that svg images work in your FF browser? Which version do you use? The latest one?

**Comment by englishextra** [comment]
The fixes you suggest have been commited to this very repo but not published on NPM. So how do you check the updates that I just made? Where do you get the js and css - if from here - then the fixes should APPLY - if from NPM - they don't for now because I didn't publish a new version today yet.

**Comment by jasomdotnet** [comment]
I got you now. You mean I download latest commit and test. OK, give me few minutes.

**Comment by jasomdotnet** [comment]
Latest commit is 14 hours old. I'm already using it. Issues are still present.

**Comment by jasomdotnet** [comment]
Sorry, I was checking wrong file. CSS is 27 minutes old. Going to test it.

**Comment by jasomdotnet** [comment]
Yes, I works!

PS: Give me please one 10 more minutes till I upload material I just completed for my latest question.
